### ISSUE TITLE
entering jobad currently does not work

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#558]
![Auswahl_449](https://user-images.githubusercontent.com/858642/73273439-45588700-41e4-11ea-99af-9b853b9d5497.png)

**Comment by cbleek** [comment]
propably related to 

https://github.com/cross-solution/YAWIK/issues/526

**Comment by kilip** [comment]
@cbleek actually #526 is already fixed and merged in this pull #547.

Do you want me to fix this issue?

**Comment by cbleek** [comment]
yes.

The [module/Core/composer.json](https://github.com/cross-solution/YAWIK/blob/master/module/Core/composer.json) still does not include the "mikemix/zf2htmlpurifier".
